<?xml version="1.0"?>
<robot name="champ" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find champ_description)/urdf/properties.urdf.xacro" />

    <material name="black"><color rgba="0.15 0.15 0.15 1.0" /></material>
    
    <!-- <link name="champ"/> -->
    <link name="base_link">
        <inertial>
            <origin xyz="0 0 0" />
            <mass value="${base_mass}" />
            <inertia ixx="${(1/12) * base_mass * (base_y_length * base_y_length + base_z_length * base_z_length)}" ixy="0.0" ixz="0.0"
                     iyy="${(1/12) * base_mass * (base_x_length * base_x_length + base_z_length * base_z_length)}" iyz="0.0"
                     izz="${(1/12) * base_mass * (base_x_length * base_x_length + base_y_length * base_y_length)}" />
        </inertial>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="${base_mesh_path}" scale="0.001 0.001 0.001" />
            </geometry>
        </collision>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://champ_description/meshes/base.stl" scale="0.001 0.001 0.001" />
            </geometry>
            <material name="black" />
        </visual>
    </link>
    <!-- <joint name="base_champ_joint" type="fixed">
        <parent link="champ" />
        <child link="base_link" />
    </joint> -->
    <gazebo reference="base_link">
        <material>Gazebo/FlatBlack</material>
    </gazebo>

    <link name="imu_link">
        <inertial>
            <mass value="0.001"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1e-09" ixy="0.0" ixz="0.0" iyy="1e-09" iyz="0.0" izz="1e-09"/>
        </inertial>
    </link>
    <joint name="imu_joint" type="fixed">
        <parent link="base_link" />
        <child link="imu_link" />
    </joint>

    <xacro:include filename="$(find champ_description)/urdf/leg.urdf.xacro" />

    <xacro:champ_leg leg="lf"/>
    <xacro:champ_leg leg="lh"/>
    <xacro:champ_leg leg="rf"/>
    <xacro:champ_leg leg="rh"/>

    <xacro:include filename="$(find common_sensors)/urdf/sensors/hokuyo_utm30lx.urdf.xacro" />
    <xacro:hokuyo_utm30lx 
        name="hokuyo" 
        parent="base_link" 
        ros_topic="scan" 
        update_rate="30" 
        ray_count="1040" 
        min_angle="130" 
        max_angle="-130" >
        <origin xyz="0.0 0.0 ${base_z_length / 2 + 0.04}" rpy="0 0 0"/>
    </xacro:hokuyo_utm30lx>
    <gazebo reference="hokuyo_frame">
		<material>Gazebo/FlatBlack</material>
	</gazebo>

    <xacro:include filename="$(find common_sensors)/urdf/sensors/xtion.urdf.xacro" />
    <xacro:sensor_xtion 
        parent="base_link" 
        camera_name="camera">
        <origin xyz="${base_x_length / 2} 0.0 ${base_z_length / 2 + 0.01}" rpy="0 0 0"/>
    </xacro:sensor_xtion>

    <gazebo reference="hokuyo_frame">
		<material>Gazebo/FlatBlack</material>
	</gazebo>

    <gazebo>
        <plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
            <robotNamespace>/</robotNamespace>
            <updateRate>50.0</updateRate>
            <bodyName>imu_link</bodyName>
            <topicName>imu/data</topicName>
            <accelDrift>0.005 0.005 0.005</accelDrift>
            <accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
            <rateDrift>0.005 0.005 0.005 </rateDrift>
            <rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
            <headingDrift>0.005</headingDrift>
            <headingGaussianNoise>0.005</headingGaussianNoise>
        </plugin>
    </gazebo>

    <gazebo>
      <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>10.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>odom/ground_truth</topicName>
            <gaussianNoise>0.01</gaussianNoise>
            <frameName>world</frameName>
            <xyzOffsets>0 0 0</xyzOffsets>
            <rpyOffsets>0 0 0</rpyOffsets>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotNamespace>/champ</robotNamespace>
            <legacyModeNS>true</legacyModeNS>
        </plugin>
    </gazebo>
</robot>
